gusto-umc/Gusto-Server

gusto/src/main/java/com/umc/gusto/domain/myCategory/entity/MyCategory.java, gusto/src/main/java/com/umc/gusto/domain/review/entity/Review.java, gusto/src/main/java/com/umc/gusto/domain/user/entity/Social.java, gusto/src/main/java/com/umc/gusto/domain/user/entity/User.java
- 일부 table의 enum 타입 field가 varchar 타입으로 생성되는 문제
- review entity의 taste(맛슐랭) field가 nullable 하도록 리팩토링
- MyCategory entity의 일부 field에 length 정보 추가
- #14 
close: #14 
버그 관련 내용은 이슈 페이지 확인해주시면 되겠습니다!
=> refactor: 일부 엔티티의 field의 @Column annotation 옵션 수정

gusto/build.gradle, gusto/src/main/java/com/umc/gusto/domain/myCategory/controller/MyCategoryController.java, gusto/src/main/java/com/umc/gusto/domain/myCategory/entity/MyCategory.java, gusto/src/main/java/com/umc/gusto/domain/myCategory/model/request/MyCategoryRequest.java, gusto/src/main/java/com/umc/gusto/domain/myCategory/model/response/MyCategoryResponse.java, gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/MyCategoryRepository.java, gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/PinRepository.java, gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryCommandService.java, gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryCommandServiceImpl.java, gusto/src/main/java/com/umc/gusto/domain/review/entity/Review.java, gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java, gusto/src/main/java/com/umc/gusto/domain/store/entity/Store.java, gusto/src/main/java/com/umc/gusto/domain/store/repository/StoreRepository.java, gusto/src/main/java/com/umc/gusto/domain/user/entity/Social.java, gusto/src/main/java/com/umc/gusto/domain/user/entity/User.java, gusto/src/main/java/com/umc/gusto/domain/user/repository/UserRepository.java
* 내 카테고리 CRUD API #7
* 내 카테고리 별 가게 목록 조회 API
- Entity 내 default 값을 요구하는 필드 위의 어노테이션에 @Builder.Default 추가
- builde.gradle `implementation 'org.springframework.boot:spring-boot-starter-security'` 주석 처리
- 내 카테고리 확인 여부(publishCategory)를 통한 조회 로직이 아직 구현되지 않았으며, 이슈에서 보다시피 위치 기반 처리는 새로운 api를 작성할 예정입니다!
close: #7
* 많은 내용 수정, 추가로 인해 충돌이 있을 수 있습니다. entity 부분 확인 부탁드립니다!
* 버그 발생 즉시 pr을 날렸어야 하는데 feature 개발 중 오류를 발견해 부득이 하게 한꺼번에 pr를 날리게 되었습니다.
=> feat : 내 카테고리 CRUD API 작성

gusto/src/main/java/com/umc/gusto/global/auth/model/OAuthAttributes.java
- #31 에서 NPE 발생 에러 수정 중 Age 정보를 처리하는 코드 일부가 누락되었습니다.
- 로그인이 불가능한 이슈로 별도의 approve 없이 바로 merge 하였습니다!
=> fix: social 로그인 시 Age 포메팅 오류 수정

gusto/.idea/.gitignore, gusto/.idea/compiler.xml, gusto/.idea/gradle.xml, gusto/.idea/jarRepositories.xml, gusto/.idea/misc.xml, gusto/.idea/modules.xml, gusto/.idea/modules/gusto.main.iml, gusto/.idea/uiDesigner.xml, gusto/.idea/vcs.xml, gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupRepository.java, gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteController.java, gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteListController.java, gusto/src/main/java/com/umc/gusto/domain/route/model/request/RouteListRequest.java, gusto/src/main/java/com/umc/gusto/domain/route/model/request/RouteRequest.java, gusto/src/main/java/com/umc/gusto/domain/route/model/response/RouteResponse.java, gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteListRepository.java, gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteRepository.java, gusto/src/main/java/com/umc/gusto/domain/route/service/RouteListService.java, gusto/src/main/java/com/umc/gusto/domain/route/service/RouteListServiceImpl.java, gusto/src/main/java/com/umc/gusto/domain/route/service/RouteService.java, gusto/src/main/java/com/umc/gusto/domain/route/service/RouteServiceImpl.java
- 루트 생성/그룹 내 루트 추가
- 루트 삭제
- 루트 리스트 항목 삭제
- Route 생성 시 RouteList 생성 비지니스 로직 호출
- RouteRequestDto에서 루트리스트 저장 값을 포함합니다
- 에러 핸들러 작업 반영하겠습니다.
close: #
=> 루트 &루트 리스트 생성, 삭제

gusto/src/main/java/com/umc/gusto/domain/user/controller/UserController.java, gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java, gusto/src/main/java/com/umc/gusto/global/auth/AuthController.java, gusto/src/main/java/com/umc/gusto/global/auth/CustomAuthenticationSuccessHandler.java, gusto/src/main/java/com/umc/gusto/global/auth/OAuthService.java, gusto/src/main/java/com/umc/gusto/global/auth/model/OAuthAttributes.java
- #48 
- 특이 사항
close: #48
해당 내용은 임시조치이며, 데모데이 이후 변경될 예정입니다. 자세한 사항은 issue 페이지 참고 부탁드립니다.
참고로 BE의 테스트 과정에는 차이가 없습니다!
=> feat: social login 결과 redirect

gusto/src/main/java/com/umc/gusto/domain/user/controller/UserController.java, gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
- 잘못된 method 호출로 StackOverFlow 가 발생하던 문제
- 잘못된 error를 throw하던 문제
=> hotfix: 닉네임 중복 확인 API 버그 수정

gusto/src/main/java/com/umc/gusto/domain/review/controller/ReviewController.java, gusto/src/main/java/com/umc/gusto/domain/review/entity/Review.java, gusto/src/main/java/com/umc/gusto/domain/review/model/request/CreateReviewRequest.java, gusto/src/main/java/com/umc/gusto/domain/review/model/request/UpdateReviewRequest.java, gusto/src/main/java/com/umc/gusto/domain/review/model/response/ReviewDetailResponse.java, gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewService.java, gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
- 리뷰 삭제 API : 소프트 삭제로 수정
- 리뷰 request, response 이너 클래스 대신 각 클래스로 수정
#37
=> refactor: 리뷰 CRUD response, request 수정 & 리뷰 하드 삭제 -> 소프트 삭제로 수정, 리뷰 생성 수정 시 이미지 저장

gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java, gusto/src/main/java/com/umc/gusto/domain/group/model/request/JoinGroupRequest.java, gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupMemberRepository.java, gusto/src/main/java/com/umc/gusto/domain/group/repository/InvitationCodeRepository.java, gusto/src/main/java/com/umc/gusto/domain/group/service/GroupService.java, gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java, gusto/src/main/java/com/umc/gusto/global/exception/Code.java
- 그룹 초대 코드를 통한 그룹 참여
- 그룹 탈퇴 (Hard-Delete)
- 그룹 참여
- 그룹 탈퇴
close: #90
=> feat: Group 참여 및 탈퇴 API

gusto/src/main/java/com/umc/gusto/domain/user/entity/User.java
- PublishRoute 필드 추가
- PublishPin -> PublishCategory 변경
- 고지 완료된 사항으로 별도의 approve 없이 merge하며, 해당 merge 이후 테스트 DB drop 후 재생성, 혹은 User Table 구조 변경을 권해드립니다.
=> refactor: User Entity

gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java, gusto/src/main/java/com/umc/gusto/domain/group/entity/Group.java, gusto/src/main/java/com/umc/gusto/domain/group/model/request/TransferOwnershipRequest.java, gusto/src/main/java/com/umc/gusto/domain/group/model/response/TransferOwnershipResponse.java, gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupMemberRepository.java, gusto/src/main/java/com/umc/gusto/domain/group/service/GroupService.java, gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java, gusto/src/main/java/com/umc/gusto/global/exception/Code.java
- 그룹 멤버에게 그룹장 권한 이전
- 그룹 소유권 이전 주체가 그룹 소유자인지 확인
- 그룹 소유권 이전 객체가 그룹 구성원인지 확인
- 그룹 소유권 이전
close: #93
=> feat: Group 소유권 이전 API

gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java
=> hotfix: 괄호 생략으로 인한 오류 수정

gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupMemberRepository.java, gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
=> hotfix:resolve conflicts(제외된 import문, 중복된 명칭)

gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java, gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
- 프론트 쪽에서 날짜 별 리뷰 분류 삭제 요청이 들어와 원상복구
- 가게 상세 조회
- 별 다른 수정사항이 없이 기존 배포된 0.1.0-alpha.4와 코드 내용이 동일해 리뷰 없이 머지합니다.
close: #142
=> refactor : 가게 조회 시 날짜 별 리뷰 분류 처리 삭제

gusto/src/main/java/com/umc/gusto/domain/myCategory/controller/MyCategoryController.java, gusto/src/main/java/com/umc/gusto/domain/myCategory/controller/PinController.java, gusto/src/main/java/com/umc/gusto/domain/myCategory/model/response/CreatePinResponse.java, gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/MyCategoryRepository.java, gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/PinRepository.java, gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryService.java, gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java, gusto/src/main/java/com/umc/gusto/domain/myCategory/service/PinService.java, gusto/src/main/java/com/umc/gusto/domain/myCategory/service/PinServiceImpl.java, gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java, gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetStoreDetailResponse.java, gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetStoreResponse.java, gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java, gusto/src/main/java/com/umc/gusto/domain/user/repository/UserRepository.java, gusto/src/main/java/com/umc/gusto/global/exception/Code.java
- 프론트 측에서 추가로 필요한 조회 사항을 처리
- 가게 조회 시 pinId, 경도, 위도를 추가로 조회합니다.
-  내가 찜하지 않은 가게인 경우 pinId 값이 오지 않으며 pin 값이 false 처리 됩니다.
- 찜 추가 시 pinId를 조회합니다.
- 가게 조회
- 찜 추가
close: #158
* refactor/myCategory 수정 내용을 pull 하면서 이전 커밋 내용이 첨가되어 있습니다. **마지막 커밋만 확인해주시면 편히 리뷰하실 수 있습니다!**
=> feat : 가게 조회 시 pinId, 경도, 위도 조회 / 찜 추가 시 해당 pinId 조회 처리

gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java, gusto/src/main/java/com/umc/gusto/domain/store/repository/StoreRepository.java, gusto/src/main/java/com/umc/gusto/domain/store/service/StoreService.java, gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
=> feat: 가게 검색 기능

.idea/compiler.xml, gusto/src/main/java/com/umc/gusto/domain/review/service/CollectReviewServiceImpl.java
이전 PR#114에서 처리한 코드가 사라져서 다시 올립니다.
#113
=> refactor: (재업로드)방문 날짜가 같은 경우, 생성 날짜를 기준으로 정렬 후 페이징 처리 

gusto/src/main/java/com/umc/gusto/domain/store/entity/Store.java
=> hotfix : longitude DOUBLE 범위 수정 취소

gusto/src/main/java/com/umc/gusto/domain/store/entity/Store.java
=> hotfix : logitude DOUBLE 범위 수정 시 categoryString 삭제 실수 해결

gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
- 가게 카테고리 값을 카테고리 테이블이 아닌 store 엔티티 안에서 사용하기로 하여 수정합니다. 
- #194
=> refactor: 가게 검색 결과의 가게 카테고리 조회 시 categoryString 컬럼을 조회하도록 수정

gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java, gusto/src/main/java/com/umc/gusto/domain/review/service/CollectReviewServiceImpl.java, gusto/src/main/java/com/umc/gusto/domain/review/service/FeedServiceImpl.java, gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
삭제된 리뷰인지 확인을 하지 않아서 다른 API에서 리뷰가 조회되고 있었습니다. 
리뷰 조회하는 API들은 모두 수정하였습니다. 
- #177
=> fix: 리뷰 조회 시 status 값을 확인하도록 수정

gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
- 리뷰 삭제 요청 시 status 값을 INACTIVE로 변경했으나 저장하지 않아서 값 변경이 반영되지 않았습니다. 
- 변경된 엔티티 저장 코드를 넣었습니다. 
#207
=> fix: 리뷰 삭제했으나 리뷰가 조회되는 상황 수정

gusto/build.gradle, gusto/src/main/java/com/umc/gusto/domain/review/entity/Review.java, gusto/src/main/java/com/umc/gusto/domain/review/model/request/CreateReviewRequest.java, gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java, gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java, gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetStoreInfoResponse.java, gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java, gusto/src/main/java/com/umc/gusto/global/exception/Code.java
=> release: 0.1.0-alpha.14

gusto/build.gradle, gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java, gusto/src/main/java/com/umc/gusto/domain/store/repository/StoreRepository.java, gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
=> release: 0.1.0-alpha.15

gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java, gusto/src/main/java/com/umc/gusto/domain/user/entity/User.java
리뷰 생성 시 user의 리뷰 수가 증가해야 하나 해당 로직이 빠져있었습니다. 이를 수정했습니다.
#218
=> fix: 리뷰 생성 시 user의 review_cnt가 증가하도록 수정

gusto/src/main/java/com/umc/gusto/domain/review/controller/ReviewController.java, gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewService.java, gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java, gusto/src/main/java/com/umc/gusto/domain/user/entity/User.java
리뷰가 삭제 되었을 때 user의 reviewCnt가 감소해야 합니다.
#219
=> fix: 리뷰 삭제 시 user의 reviewCnt가 감소하도록 수정

gusto/src/main/java/com/umc/gusto/domain/myCategory/service/PinServiceImpl.java, gusto/src/main/java/com/umc/gusto/domain/user/entity/User.java
- 찜한 경우 user의 pinCnt가 증가, 찜 삭제를 한 경우 user의 pinCnt가 감소
close: #221
=> fix : 찜한 경우 user의 pin_cnt가 증가하도록 변경

gusto/src/main/java/com/umc/gusto/domain/myCategory/controller/MyCategoryController.java, gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/MyCategoryRepository.java, gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/PinRepository.java, gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryService.java, gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java, gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
- 데모데이 이후 카테고리 조회 시 페이징 처리를 하였습니다.
- 카테고리 조회 시 7개씩 페이징 처리
- 카테고리 속 가게 조회시 5개씩 페이징 처리
close: #232
=> feat : 페이징 작업(내 카테고리)

gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java, gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupMemberRepository.java, gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupRepository.java, gusto/src/main/java/com/umc/gusto/domain/group/service/GroupService.java, gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
- 그룹 목록: 5개씩 페이징 처리
- 그룹 구성원 목록: 10개씩 페이징 처리
close: #234
=> feat: 커서 페이징 작업 (그룹 목록/ 그룹 구성원 목록)

gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java, gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupListRepository.java, gusto/src/main/java/com/umc/gusto/domain/group/service/GroupService.java, gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java, gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteRepository.java
- 그룹 내 찜한 식당 페이징 : 커서 기반  페이징으로 초기값 8개, 추가 페이징 6개씩  오름차순 정렬
- 동작 
close: #231
=> feat:그룹 내 찜한 식당 페이징 : 커서 기반 오름차순 정렬로 다음 찜한 식당 전달

gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupListRepository.java
=> fix:그룹 내 찜한 식당 페이징 오타 수정

gusto/src/main/java/com/umc/gusto/domain/user/controller/UserController.java
- 로그인 api의 엔드 포인트가 설계(/users/sign-in)와 다르게 적용되어 있어(/users/sign-up)
회원가입 api와 중복 매핑 오류가 발생했습니다.
- develop 브랜치로 동일 내용의 PR이 생성될 예정입니다.
=> hotfix: 로그인 api의 엔드 포인트 수정

gusto/src/main/java/com/umc/gusto/domain/user/model/request/UpdateProfileRequest.java, gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
- 프로필 수정 화면의 항목이 확정됨에 따라 기존 수정 API에 닉네임 필드를 추가하였습니다.
=> feat: 프로필 수정 API에 닉네임 필드 포함

gusto/src/main/java/com/umc/gusto/domain/route/model/response/RoutePagingResponse.java, gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteRepository.java, gusto/src/main/java/com/umc/gusto/domain/route/service/RouteServiceImpl.java
=> Bug: hasNext 오타 수정

gusto/src/main/java/com/umc/gusto/domain/user/model/request/SignInRequest.java, gusto/src/main/java/com/umc/gusto/domain/user/model/request/SignUpRequest.java, gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java, gusto/src/main/java/com/umc/gusto/global/auth/AuthController.java, gusto/src/main/java/com/umc/gusto/global/auth/CustomAuthenticationSuccessHandler.java, gusto/src/main/java/com/umc/gusto/global/auth/OAuthService.java, gusto/src/main/java/com/umc/gusto/global/auth/service/JwtService.java, gusto/src/main/java/com/umc/gusto/global/auth/service/OAuthService.java, gusto/src/main/java/com/umc/gusto/global/auth/service/SocialService.java, gusto/src/main/java/com/umc/gusto/global/auth/service/UserDetailsService.java, gusto/src/main/java/com/umc/gusto/global/exception/Code.java
- 기존 oauth 로그인 방식에 보안 상 취악사항이 존재하여 이를 보완할 수 있도록 수정하였습니다.
문제 상황 및 수정 내용은 다음 노션 문서 확인해주시면 됩니다.
https://www.notion.so/d60a715460384bfcb1ef10ebce946339?pvs=4
- 해당 PR 병합 이후, 소셜 로그인 방식이 변경되므로 서버 테스트 시 변경된 내용에 대해 숙지가 필요합니다. 아래 문서에서 확인하실 수 있습니다.
https://www.notion.so/for-Server-50d018fc6a1c43959cd20fcb7f180d6a?pvs=4
=> feat: oauth 로그인 방식 변경

gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java, gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetPinStoreInfoResponse.java, gusto/src/main/java/com/umc/gusto/domain/store/service/StoreService.java, gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
- 현재 지역의 찜한 방문 식당 조회
- 현재 지역의 찜한 미방문 식당 조회
- 5개씩 페이징 처리
- 현재 지역의 찜한 방문 식당 조회
- 현재 지역의 찜한 미방문 식당 조회
close: #272
=> feat: 현재 지역의 찜한 방문/미방문 식당 조회

gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java, gusto/src/main/java/com/umc/gusto/domain/group/service/GroupService.java, gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java, gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java, gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java, gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java, gusto/src/main/java/com/umc/gusto/domain/store/service/StoreService.java, gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
- 기존에 토큰을 받지 않고 있어, 토큰 추가로 API 시트 개선 : 맛집 검색 엔진,그룹 내 찜 식당 목록 조회
- user Parameter를 제공하지 않은 오류에 영향을 받아 수정한 API : 카테고리 별 가게 목록 조회, 가게 조회,가게 1건 상세 조회,현재 지역의 찜한 식당 방문 여부 조회,현재 지역의 찜한 미방문 식당 조회
- 그룹 내 식당 조회
- 맛집 검색 엔진
- 현재 지역의 찜한 미방문 식당 조회
- 가게 상세 정보 조회(리뷰 페이징)
- 내 카테고리 별 가게 목록 조회
- 빠른 오류 수정 및 적용을 위해서 포스트맨 시행 시, 내부 데이터가 없는 값들을 다 넣어서 테스트하기 보다, 로직 상에 문제가 없어서 빈 데이터로 반환되는 것을 검증한 API가 있습니다.
close: #
=> [hotfix] user Parameter를 미제공으로 인한 오류 수정 

gusto/src/main/java/com/umc/gusto/domain/user/model/request/PublishingInfoRequest.java, gusto/src/main/java/com/umc/gusto/domain/user/repository/UserRepository.java, gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
=> refactor: 코드 리팩토링(transaction, 필드명 변경 등)

gusto/src/main/java/com/umc/gusto/domain/user/controller/UserController.java, gusto/src/main/java/com/umc/gusto/domain/user/model/request/PublishingInfoRequest.java, gusto/src/main/java/com/umc/gusto/domain/user/model/request/SignInRequest.java, gusto/src/main/java/com/umc/gusto/domain/user/model/request/SignUpRequest.java, gusto/src/main/java/com/umc/gusto/domain/user/model/request/UpdateProfileRequest.java, gusto/src/main/java/com/umc/gusto/global/auth/service/JwtService.java, gusto/src/main/java/com/umc/gusto/global/exception/handler/GlobalExceptionHandler.java
- request에 대한 validation 설정
- validation 설정 중 `@Validated` 어노테이션 활용 중 발생하는 `ConstraintViolationException`에 대하여 error 템플릿에 상이한 결과를 return하는 것을 확인, 이를 수정함
- @yujiyea 에러 핸들러 부분을 꼼꼼히 살펴봐주세요!! 감사합니다
=> refactor: valid & validated 처리, ConstraintViolationException 핸들러 수정

gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/PinRepository.java
- #308 PR merge 시 pinRepository에서 오류 발생
- #319 PR에서 리팩토링된 메서드명이 `#308` PR에서 롤백 되었음. 
-> pinRepository를 `#319`로 되돌림
- 동일한 문제가 발생하지 않도록 PR을 merge하기 전에 작업한 branch의 base를 원본 레포지토리의 
develop branch와 동일하게 만든 후 merge 부탁드립니다~! @yujiyea @Hwater00 @Jeonghee-Han @kchaeeun
=> hotfix: #308 PR에서 commit된 오타 수정

gusto/src/main/java/com/umc/gusto/domain/review/service/CollectReviewServiceImpl.java
repository.find 할 때 NotFoundException을 터트려서 빈 리스트 대신 에러 응답을 반환하고 있었습니다.
orElseThrow 대신 orElse에서 빈 값 반환 + hasNext값 false로 설정하도록 수정했습니다.
close: #
=> refactor: 리뷰 피드 API 조회 실패 시 빈 리스트 반환하도록 수정
