gusto/src/main/java/com/umc/gusto/global/exception/Code.java
gusto/src/main/java/com/umc/gusto/global/exception/ExceptionResponse.java
gusto/src/main/java/com/umc/gusto/global/exception/GeneralException.java
gusto/src/main/java/com/umc/gusto/global/exception/customException/TempException.java
gusto/src/main/java/com/umc/gusto/global/exception/handler/GlobalExceptionHandler.java

에러 핸들러 생성
예외 발생 시 응답 형태는 아래와 같도록 했습니다. 
```
{ 
"success": false,
"errorCode": 4100,
"message": "잘못된 요청입니다."
}
```
예외 응답은 변경이 필요없기 때문에 record로 만들어서 데이터 가공 시 중간에 변질될 우려가 없도록 했습니다. 
연관된 Issue: #19 
저희가 응답 형태를 의논하지 않아서 다들 아는 워크북을 기준으로 에러핸들러를 수정해서 만들었습니다. 
하지만,  에러 핸들러를 공부하다보니 정해야하는 부분이 있는 것 같아 노션에 정리해두겠습니다.
노션 문서를 보시고 의견을 주시면 코드를 수정하도록 하겠습니다!

feat : RestControllor를 이용한 에러 핸들러

---

gusto/build.gradle
gusto/src/main/java/com/umc/gusto/global/auth/CustomAuthenticationSuccessHandler.java
gusto/src/main/java/com/umc/gusto/global/auth/OAuthService.java
gusto/src/main/java/com/umc/gusto/global/auth/model/OAuthAttributes.java

- 소셜 로그인 시 정보 제공 항목 일부 미동의 시 NPE(NullPointException)이 발생하던 문제
- 최초 로그인 시 user의 소셜 정보에 provider의 user 식별자가 노출되던 문제
- 최초 로그인 시 반환하는 response body의 구조를 변경
- 소셜 로그인 시 정보 제공 항목 일부 미동의 시 버그가 발생하던 문제
- Optional class를 활용하여 NPE가 발생할 수 있는 resource를 명시
- Optional.ifPresent() 를 사용, null이 아닌 경우에만 데이터 parsing을 진행
- 최초 로그인 시 user의 소셜 정보에 provider의 user 식별자가 노출되던 문제
- `@JsonIgnore` 어노테이션을 활용하여 json 직렬화 시 id 값을 제외
- 최초 로그인 시 반환하는 response body의 구조를 변경
- 기존 항목의 `result`에 해당하는 값만 return 하도록 변경
close: #21

fix: 소셜 로그인 동의 여부 관련 버그, provider Id가 노출되던 문제

---

gusto/src/main/java/com/umc/gusto/domain/user/UserService.java
gusto/src/main/java/com/umc/gusto/domain/user/UserServiceImpl.java
gusto/src/main/java/com/umc/gusto/domain/user/model/NicknameBucket.java
gusto/src/main/java/com/umc/gusto/domain/user/model/response/FirstLogInResponse.java
gusto/src/main/java/com/umc/gusto/global/auth/CustomAuthenticationSuccessHandler.java
gusto/src/main/java/com/umc/gusto/global/auth/OAuthService.java

- 랜덤 닉네임 생성 로직
- 중복 닉네임 생성을 최대한 방지하기 위해 Default 닉네임의 모든 요소를 랜덤하게 선택하지 않고,
`형용사` 풀과 `메뉴명` 풀이 각각 회전하도록 하였습니다.
- 현재 `형용사` 풀(bucketA) 에는 20개의 item이, `메뉴명` 풀(bucketB)에는 21개의 item이 존재합니다.
- `bucketA`
```java
public static final String[] bucketA = {
"귀여운", "용맹한", "용감한", "엘레강스한", "웃기는",
"즐거운", "청량한", "고지식한", "산뜻한", "똑똑한",
"명랑한", "상쾌한", "깨끗한", "노래하는", "소심한",
"의심하는", "어지러운", "혼란스러운", "빛나는", "천진난만한"
};
``` 
- `bucketB`
```java
public static final String[] bucketB = {
"파스타", "뇨끼", "비빔밥", "곰탕", "감자탕",
"수플레", "짬뽕", "탕수육", "야채곱창", "피자",
"샐러드", "족발", "바질페스토", "도토리묵", "전복죽",
"계란말이", "닭볶음탕", "추어탕", "단팥빵", "치즈케이크",
"에그타르트"
};
``` 
- 해당 bucket들을 한칸씩 슬라이딩하여 메뉴명을 조합하게 되면, 20과 21이 서로소(공약수가 1 뿐인 수) 관계에 있으므로 20 * 21개의 가능한 모든 경우의 수가 조합된 뒤에 최초 닉네임(`귀여운 파스타`)과 동일한 닉네임이 생성됩니다.
- 위의 로직으로 생성된 닉네임에 1부터 999까지의 랜덤 난수를 생성해 …

feat: 랜덤 닉네임 생성

---

gusto/src/main/java/com/umc/gusto/domain/user/controller/UserController.java

API 설계서와 다르게 작성되었음
- API 설계서(GET)과 다르게 작성되었음.
- `@PostMapping`에서 `@GetMapping`으로 변경하는 단순 작업이므로 별도의 approve 없이 바로 merge

fix: 닉네임 중복체크 API의 method 변경(POST -> GET)

---

gusto/src/main/java/com/umc/gusto/domain/route/service/RouteServiceImpl.java
gusto/src/main/java/com/umc/gusto/domain/store/repository/StoreRepository.java
gusto/src/main/java/com/umc/gusto/domain/user/repository/UserRepository.java
gusto/src/main/java/com/umc/gusto/global/util/S3Controller.java
gusto/src/main/java/com/umc/gusto/global/util/S3Service.java

- #39 에서 프로필 이미지처럼 단일 이미지만 저장하는 경우 List에서 값을 한 번 더 가져오는 로직이 필요함으로 이를 해소하기 위함 추가 작업을 진행했습니다. 
- 테스트 후 이미지 편리한 삭제를 위해 로그에 파일명이 출력됩니다.랜덤값.png로 확장자까지 이름에 포함됩니다.
- uploadImages()를 통해 다수의 이미지를 저장
- uploadImage()로 단일 이미지를 저장
close: #53 
<의견이 필요한 부분>
1.S3 업로드 실패도 GeneralException을 사용할까요?
2. 이미지만 저장하기 위해 현재 s3버킷 정책을 설정하는데, 코드에서 확장자 처리를 하면 에러 발생 시 메세지가 나오지만 버킷은 정책 외에 확장자는 빼고 저장합니다. 버킷 정책과 코드 중 어떤 방법으로 확정할 것인지 고민입니다.

refactor:  단일 이미지, 다수 이미지 로직 분리 

---

gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java
gusto/src/main/java/com/umc/gusto/domain/group/model/response/GetGroupsResponse.java
gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupListRepository.java
gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupMemberRepository.java
gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupRepository.java
gusto/src/main/java/com/umc/gusto/domain/group/service/GroupService.java
gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteRepository.java

- 그룹 목록 조회 API
- 그룹 구성원 조회 API
- 기존 그룹 1건 조회 API에서 그룹 구성원 조회 메소드를 사용하도록 코드 수정
- 그룹 목록 조회
- 그룹 구성원 조회
close: #80

feat: Group 목록 및 구성원 조회 API

---

gusto/build.gradle
gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java
gusto/src/main/java/com/umc/gusto/domain/group/entity/InvitationCode.java
gusto/src/main/java/com/umc/gusto/domain/group/model/response/GetInvitationCodeResponse.java
gusto/src/main/java/com/umc/gusto/domain/group/repository/InvitationCodeRepository.java
gusto/src/main/java/com/umc/gusto/domain/group/service/GroupService.java
gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
gusto/src/main/java/com/umc/gusto/global/exception/Code.java

- 초대 코드: 대문자, 소문자, 숫자를 포함한 임의의 12자리 문자열
- 그룹 생성 시 한 그룹 당 영구 초대 코드 하나 발급
- 그룹 초대 코드 조회
- 그룹 초대 코드 조회
close: #86

feat: Group 초대코드 생성 및 조회 API

---

gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java

리뷰 수정 시 request에 이미지가 없을 때 null값인 list를 isEmpty() 비교해서 null 오류가 발생했습니다.
해당 부분을 null 체크하는 것으로 변경했습니다. 
- 요청 값에 이미지가 null인지 체크
#37

refactor: 리뷰 수정 시 이미지를 요청에서 주지 않았을 경우 오류 발생하는 부분 수정

---

gusto/src/main/java/com/umc/gusto/domain/store/entity/City.java
gusto/src/main/java/com/umc/gusto/domain/store/entity/Town.java

- 참조 데이터 변경으로 인한 조치
- 해당 PR merge 이후 minnie schema에서 곧바로 데이터베이스를 매핑하지 못할 수 있습니다.
- 해당 문제는 0.1.0-alpha.4 버전 배포시 db의 schema를 직접 변경한 이후 조치될 예정입니다.

chore: city, town 엔티티의 code field 길이 변경

---

gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java
gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetStoreDetailResponse.java
gusto/src/main/java/com/umc/gusto/domain/store/service/StoreService.java
gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java

- 가게 조회를 통한 리뷰 조회 시 날짜별로 sort되어 보여지기 때문에 날짜별로 조회되도록 return 값 수정이 있습니다.
- Map을 사용해 visitedAt를 기준으로 분류해서 조회
- 최신 방문일자를 기준으로 sort를 하니 reviewId만 받아 페이징 할때 혼동이 있어, visitedAt까지 쿼리로 받아 페이징 처리해씁니다.
- reviewId가 null 일때 3개의 리뷰를 조회해야하는데, null이 아닐 때 3개를 조회해와 상수 사용 변경이 있습니다.
- 가게 조회 시 리뷰 날짜별 조회
close: #119
* 변경된 `@Query`을 봐주시면 될거 같습니다.

refactor : 가게 상세 조회 시 리뷰 날짜별 분류 처리

---

gusto/src/main/java/com/umc/gusto/global/exception/ExceptionResponse.java
gusto/src/main/java/com/umc/gusto/global/exception/handler/GlobalExceptionHandler.java

@Valid로 유효성 검사한 부분이 예외핸들러에서 잡지 못해서 @Valid에 적어둔 메시지가 넘어가지 않았습니다. 
잘못된 요청이라는 메세지와 함께 @Valid에서 더 자세히 적어준 메세지도 넘기도록 했습니다.
```
{
"errorCode": 400,
"message": "잘못된 요청입니다.",
"result": {
"storeId": "storeId는 null일 수 없습니다."
}
}
```
#19

refactor: @Valid 에러를 체크하지 못하는 부분 수정

---

gusto/src/main/java/com/umc/gusto/domain/user/controller/UserController.java
gusto/src/main/java/com/umc/gusto/domain/user/entity/User.java
gusto/src/main/java/com/umc/gusto/domain/user/model/request/PublishingInfoRequest.java
gusto/src/main/java/com/umc/gusto/domain/user/model/response/FeedProfileResponse.java
gusto/src/main/java/com/umc/gusto/domain/user/model/response/ProfileResponse.java
gusto/src/main/java/com/umc/gusto/domain/user/model/response/PublishingInfoResponse.java
gusto/src/main/java/com/umc/gusto/domain/user/service/UserService.java
gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java

- 아래 화면에 대한 API 입니다.
- 화면에 대한 값을 출력합니다. (나이, 성별 정보 역시 포함하여 전송됩니다.)
close: #128 
Spring Security 로직 상 프로필 정보를 return하기 위해 User 정보 조회를 추가로 거치지 않습니다.
따라서 Controller에서도 충분히 정보 처리가 가능하지만, Service단에서 DTO로의 변환이 이루어집니다.
저희 코드 전반적으로 DTO를 위한 Converter class를 따로 사용하지 않아 별도의 business logic이 존재하지 않음에도
Service단에서 처리를 하였는데, 다른 의견이 있으신지 궁금합니다!

feat: 프로필 정보 조회 API

---

gusto/src/main/java/com/umc/gusto/global/auth/AuthController.java
gusto/src/main/java/com/umc/gusto/global/auth/JwtService.java
gusto/src/main/java/com/umc/gusto/global/exception/Code.java
gusto/src/main/java/com/umc/gusto/global/util/RedisService.java

- Access-Token (X-AUTH-TOKEN) 만료 시 Access-Token을 재발급 받을 수 있는 API입니다.
- 만료된 X-AUTH-TOKEN과 refresh-token을 헤더로 모두 요구합니다.
- refresh-token 역시 만료되었다면 재로그인을 해야 합니다.
close: #63

feat: access token 재발급 API

---

gusto/src/main/java/com/umc/gusto/domain/group/model/response/GetGroupsResponse.java
gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java

- 그룹 목록 조회 시 사용자가 그룹의 소유자인지 여부를 확인하여 해당 정보를 반환하도록 리펙토링
- 이유: 프론트엔드 요구(그룹 리스트 페이지에서 그룹장에게만 그룹 삭제 버튼이 뜸)
- getUserGroups 메소드에서 그룹의 소유자 여부를 확인하여 GetGroupsResponse에 반영하는 코드를 추가
- 그룹 목록 조회 시 사용자가 그룹의 소유자인 경우에는 true를, 아닌 경우에는 false를 반환
close: #135

refactor: 그룹 목록 조회 시 그룹장 여부 반환

---

gusto/src/main/java/com/umc/gusto/domain/myCategory/model/request/CreateMyCategoryRequest.java
gusto/src/main/java/com/umc/gusto/domain/myCategory/model/response/MyCategoryResponse.java
gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java

- 내 카테고리 수정 시 카테고리 설명 조회가 필요해 myCategoryScript를 추가했습니다.
- 내 카테고리 수정 시 myCategoryName를 변경하지 않더라도 기본 값에 대해 중복으로 인식하는 오류가 있어 수정했습니다.
- 카테고리 전체 조회 & 위치 기반 내 카테고리 전체 조회
- 카테고리 수정(카테고리의 이름이 아닌 다른 필드를 수정 시 카테고리 이름을 중복으로 인식 못하게 변경)
close: #139

refactor : 내 카테고리 조회 시 myCategoryScript 추가 조회 / fix : 카테고리 수정 시 중복이름 버그 수정

---

gusto/src/main/java/com/umc/gusto/domain/user/model/response/ProfileResponse.java
gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
gusto/src/main/java/com/umc/gusto/global/auth/OAuthService.java

- 프로필 이미지 return : 프로필 이미지 내역이 프로필 정보 조회 시 누락되어 있어 수정하였습니다
- default 이미지 properties 값 수정
- 디폴트 프로필 이미지와 디폴트 리뷰 이미지를 동일하게 사용함에 따라 `default.img.url.profile`였던 properties key 값을 `default.img.url`으로 변경하여 공통 리소스로 관리하도록 하였습니다.
- 해당 PR merge 이후 application.properties 파일 교체가 필요합니다. 노션 문서 확인 후 교체 부탁드립니다.

feat: 프로필 정보 조회 시 프로필 이미지 return / refactor: default img 관련 처리

---

gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java

기존에는 리뷰 생성 시 이미지 값이 null이면 이미지를 아예 저장하지 않았음
리뷰 생성 시 이미지 값이 null이면 디폴트 이미지로 저장하도록 수정
#37

refactor: 리뷰 생성 시 이미지 값이 null이면 디폴트 이미지로 저장하도록 수정

---

gusto/src/main/java/com/umc/gusto/domain/group/model/response/GroupListResponse.java
gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteController.java
gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteListController.java
gusto/src/main/java/com/umc/gusto/domain/route/model/response/RouteListResponse.java
gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteRepository.java
gusto/src/main/java/com/umc/gusto/domain/route/service/RouteListServiceImpl.java
gusto/src/main/java/com/umc/gusto/domain/route/service/RouteServiceImpl.java
gusto/src/main/java/com/umc/gusto/domain/store/entity/City.java

- 기존 식당 대표 이미지가 단순 profileImage로 되어 있어 변수 네이밍 측면에서 정보 전달에 혼동을 유발했음
- 그룹 내 식당을 추가한 유저의 프로필 이미지 정보를 추가함
- 식당 상세 조회 편리성을 위해 식당 식별값을 응답 시 추가함
Bug로 인한 기존 PR이 존재함으로 이전 develop으로 롤백 시 버그 해결에 문제가 발생할 가능성을 고려해 Bug 해결 후,
#123 해당 pr 이후 반영할 예정임. 
close: #124

refactor/rename :그룹 내 식당 정보 조회 시 식당 대표 이미지, 추가한 유저 프로필 전달

---

gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java

- 현재 API 설계 상 로그인 시 token 외 추가적인 정보를 반환하고 있지 않아 본인의 닉네임을 조회하는 데 어려움이 있습니다.
- 로그인 시 닉네임(식별정보)를 반환하게 되면 token을 사용하는 주된 이유인 `stateless`에 위배가 됩니다.
- 따라서 자기 자신의 정보 조회 시, 본인의 닉네임 대신 예약된 키워드인 `my`를 사용하도록 하였습니다.
- `my` 키워드를 예약 키워드로 사용하기 위해, `my`의 닉네임 생성이 제한됩니다.
- 빠른 배포를 위해 merge 처리 먼저 하도록 하겠습니다. 차후 review, 혹은 확인했다는 이모지 달아주시면 될 것 같습니다.

feat: 먹스또 프로필 - 본인 조회 시, 닉네임이 아닌 키워드를 사용하도록 대체

---

gusto/src/main/java/com/umc/gusto/domain/review/model/response/ReviewDetailResponse.java
gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java

리뷰의 해시태그가 ID가 아닌 해시태그 엔티티 주소 값이 응답으로 넘어가고 있었습니다. ID를 반환하도록 수정하였습니다. 
#37

fix: 해시태그 id가 아닌 엔티티 주소 값이 넘어가는 상황 수정

---

gusto/src/main/java/com/umc/gusto/domain/user/entity/User.java
gusto/src/main/java/com/umc/gusto/domain/user/model/response/FeedProfileResponse.java
gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java

- 먹스또 프로필 화면이 변경됨에 따라 설계를 변경하였습니다.
- 기존 화면
- 변경 화면
- following 수 관리를 위해 **user entity에 following 필드가 추가되었습니다.**
- follow / unfollow 시 following 필드가 갱신됩니다.
- **해당 PR merge 이후 user 엔티티 변경이 필요합니다.**

feat: 먹스또 프로필 조회 시 팔로잉 수 반환

---

gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java
gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupRepository.java
gusto/src/main/java/com/umc/gusto/domain/group/service/GroupService.java
gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
gusto/src/main/java/com/umc/gusto/global/exception/Code.java

- 그룹 참여 시 사용자가 groupId를 알 수 없으므로 초대 코드만으로 가입할 수 있도록 수정
- 그룹 참여 시 이미 참여한 사용자에 한하여 예외처리 필요
- 그룹에 가입할 때 그룹 ID 필요없이 초대 코드만을 사용하도록 수정
- 이미 그룹에 가입한 유저가 다시 가입하려고 할 때 예외 처리 추가
- 초대 코드로만 그룹 참여 (최초 가입)
- 초대 코드로만 그룹 참여 (이미 가입한 경우 예외처리)
close: #155

feat: 초대 코드로 그룹 참여 및 중복 가입 예외 처리 추가

---

gusto/src/main/java/com/umc/gusto/domain/myCategory/controller/MyCategoryController.java
gusto/src/main/java/com/umc/gusto/domain/myCategory/entity/MyCategory.java
gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/MyCategoryRepository.java
gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/PinRepository.java
gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryService.java
gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java
gusto/src/main/java/com/umc/gusto/domain/myCategory/service/PinServiceImpl.java
gusto/src/main/java/com/umc/gusto/domain/user/repository/UserRepository.java
gusto/src/main/java/com/umc/gusto/global/exception/Code.java

- 서버가 클라이언트의 상태를 보존하지 않기 위해 **내 카테고리 조회 시 닉네임을 사용하지 않습니다**.
- 위의 사항으로 인해 위치 기반 처리 시 reponse가 달라지는 부분이 없어, 위치 기반에 따라 작성했던 API를 기본 조회 API에서 조회될 수 있도록 통일했습니다. 
- 내 카테고리 조회 시 nickname을 받지 않는 경우가 발생해 쿼리로 받도록 엔드포인트를 변경했습니다.
- 내 닉네임을 통해 카테고리, 찜 가게 목록 조회가 불가능합니다.
close: #157
* 위치 기반이 아닌 경우와 위치 기반인 경우를 통합해 API를 작성했습니다. 도중 신경 쓰지 못한 예외사항 있을 수 있으니 리뷰 부탁드립니다!

refactor : 위치 여부에 상관 없이 API 통일 / 내 카테고리 조회 시 토큰으로 처리 

---

gusto/src/main/java/com/umc/gusto/domain/review/controller/FeedController.java
gusto/src/main/java/com/umc/gusto/domain/review/model/response/SearchFeedResponse.java
gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
gusto/src/main/java/com/umc/gusto/domain/review/service/FeedService.java
gusto/src/main/java/com/umc/gusto/domain/review/service/FeedServiceImpl.java

- 피드 검색 시 맛집 이름 검색
- 맛집 이름 + 해시태그 검색
리뷰 가게가 구스또 파스타 가게이고 해시태그가 4인 리뷰를 반환합니다.
- 해시태그 검색
- Like in이 없어서 for문으로 여러 개의 해시태그를 검색합니다.
- 아직 페이징 처리가 되어 있지 않습니다.
#163

feat: 피드 검색 기능

---

gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java
gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetStoreResponse.java
gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java

- 리턴 값 통일을 위해 리뷰 이미지가 없는 경우 null이 아닌 ""처리를 합니다
- 카테고리 별 가게 목록 조회
- 가게 조회
- 가게 상세 조회
close: #167

refactor : 리뷰 이미지가 없는 경우 "" 처리

---

gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetStoreResponse.java
gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java

- 가게 정보 return 시 가게 이미지를 가장 좋아요가 많은 리뷰 이미지로 반환
- but 리뷰 이미지가 없을 경우 기존에는 null을 반환했음 >> null이 아닌  ""로 반환하도록 통일 및 수정
- 위도&경도 데이터타입이 Double로 통일되지 않은 부분을 확인하여 수정
- 리뷰가 없을 경우 ""로 반환
close: #167

refactor: 리뷰 이미지가 없을 경우 null이 아닌 ""로 반환

---

gusto/src/main/java/com/umc/gusto/domain/review/controller/FeedController.java
gusto/src/main/java/com/umc/gusto/domain/review/model/response/FeedDetailResponse.java
gusto/src/main/java/com/umc/gusto/domain/review/repository/LikedRepository.java
gusto/src/main/java/com/umc/gusto/domain/review/service/FeedService.java
gusto/src/main/java/com/umc/gusto/domain/review/service/FeedServiceImpl.java
gusto/src/main/java/com/umc/gusto/global/exception/Code.java

리뷰 1건 조회 API과 똑같은 로직에서 리뷰의 작성자 정보, 해당 리뷰를 보는 유저가 좋아요를 한 적이 있는지 여부 데이터 포함하도록 만들었습니다. 
#172 
리뷰 1건 조회 API와 비즈니스 로직은 거의 다른게 없기 때문에 중복 코드가 발생합니다. 따로 함수로 빼고 싶으나 review, hashTag 두개의 값을 return해야하기 때문에 좋은 코드가 생각이 안나서 수정하지 못했습니다.

feat: 피드 상세 조회 API

---

gusto/src/main/java/com/umc/gusto/domain/review/model/response/ReviewDetailResponse.java
gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java

- 리뷰 생성할 때, 해시 태그를 입력하지 않아도 되지만, 현재는 해시 태그를 입력하지 않으면 에러가 발생했습니다. 
- 리뷰 조회할 때, 리뷰의 해시 태그가 없을 경우 에러가 발생했습니다. 
해당 부분을 해시 태그과 관련없이 생성, 조회가 가능하도록 했습니다. 
close: #37

fix: 리뷰 생성과 조회 시 해시 태그가 없으면 에러 발생하는 부분 수정

---

gusto/src/main/java/com/umc/gusto/domain/review/model/response/BasicViewResponse.java
gusto/src/main/java/com/umc/gusto/domain/review/model/response/CalendarViewResponse.java
gusto/src/main/java/com/umc/gusto/domain/review/model/response/RandomFeedResponse.java

인스타뷰, 캘린더뷰, 타인 리뷰 모아보기, 먹스또 랜덤 피드는 대표 이미지 한 개만 필요합니다. 
기존에는 리뷰의 모든 이미지를 보내서 서버 부하를 줄이고자 변경했습니다.
응답 이미지 데이터 형태 변경
#152

refactor: 리뷰 대표 이미지만 넘기도록 수정

---

gusto/src/main/java/com/umc/gusto/domain/store/entity/Store.java

- 가게 정보 API를 불러오는 과정에서 간단한 처리를 위해 category 테이블에서 매핑 값을 가져오는 대신 store entity에 categoryString을 필드로 생성해 사용한다.
close: #176

refactor : store entity 내에 categoryString 추가

---

gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteController.java
gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteListController.java
gusto/src/main/java/com/umc/gusto/domain/route/model/request/ModifyRouteRequest.java
gusto/src/main/java/com/umc/gusto/domain/route/model/request/RouteListRequest.java
gusto/src/main/java/com/umc/gusto/domain/route/model/request/RouteRequest.java
gusto/src/main/java/com/umc/gusto/domain/route/model/response/RouteListResponse.java
gusto/src/main/java/com/umc/gusto/domain/route/model/response/RouteRouteListResponse.java
gusto/src/main/java/com/umc/gusto/domain/route/service/RouteListService.java
gusto/src/main/java/com/umc/gusto/domain/route/service/RouteListServiceImpl.java
gusto/src/main/java/com/umc/gusto/domain/route/service/RouteService.java
gusto/src/main/java/com/umc/gusto/domain/route/service/RouteServiceImpl.java
gusto/src/main/java/com/umc/gusto/domain/user/repository/UserRepository.java
gusto/src/main/java/com/umc/gusto/global/exception/Code.java

- PUBLIC_REVIWE 컬럼 반영하기 위해 리뷰 정보 가져오는 로직 통일수정
- 원활한 차후 관리를 위해 API 경로 주석 작성
- 통일성 부여를 위해 아직 남아있던 이너 클래스 수정
- 루트 수정 시 수정할 항목만 입력 받도록 하기 위해서는 routeList가 빈 배열 형태 유지가 필수적인데 이를 입력 시 front 처리에서 수정할 항목만 받을 수 있도록 Beckend에서 처리하도록 함
- 프론트엔드 요청 사항에 따라 루트 내 항목 삭제 시 이동 순서를 자동으로 조절하도록 수정
- 루트 수정 시 만약 루트명만 입력하면 리스트 미 작성 시 NullPointerException 발생을 막기 위해 setter 추가
- DTO에 setter가 추가되었는데  front에서 처리하지 않으면서도 setter가 없을 수 있는 List.size() null 관련 다른 방안을 알고 계시다면 조언해주세요
close: #116

feat:루트 내 경로 항목 삭제 시 자동으로 순서 조정  /refactor:루트 리팩토링(DTO형식,API 주석)

---

gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetStoreDetailResponse.java
gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java

- store의 category 값을 store엔티티에서 사용하게 되어 이와 같이 수정합니다.
- 가게 상세 조회
- 이와 동일한 로직이 있는 @yujiyea @Jeonghee-Han 두분 수정이 필요합니다!
close: #180

refactor : 가게 상세 조회 시 카테고리 categoryString을 조회

---

gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java
gusto/src/main/java/com/umc/gusto/domain/store/service/StoreService.java
gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java

- 방문 날짜의 경우 현재 날짜가 아닐 수 있기 때문에 visitedAt과 reviewId을 기준으로 최신순 조회를 한다
- 리뷰 조회 시 status가 ACTIVE인지 확인하고 처리한다.
- 방문 날짜를 기준으로 리뷰를 조회한다
- 리뷰 페이징 시 visitedAt를 추가 쿼리로 받는다.
- 가게 상세 조회
close: #184

refactor : 리뷰 조회 시 status을 거치도록 수정 / 방문 날짜를 기준으로 리뷰 조회

---

gusto/src/main/java/com/umc/gusto/domain/review/model/response/FeedDetailResponse.java
gusto/src/main/java/com/umc/gusto/domain/review/service/FeedServiceImpl.java

- 피드 상세 보기 API에서 리뷰의 해시태그가 없을 때 상세보기 에러가 발생했습니다. 해시태그가 없는데 length()-1을 했습니다.
- 프론트에서 처리하기 쉽게 해시태그를 List로 반환합니다.  
해시태그를 List로 반환하도록 하여 length()-1을 하지 않도록 변경되었습니다. 
#172

fix: 피드 상세 보기 API에서 리뷰의 해시태그가 없을 때 상세보기 에러가 발생하는 부분 해결 & 프론트에서 편하게 List로 해시태그 id값 반환

---

gusto/src/main/java/com/umc/gusto/domain/review/model/request/CreateReviewRequest.java
gusto/src/main/java/com/umc/gusto/domain/review/model/request/UpdateReviewRequest.java
gusto/src/main/java/com/umc/gusto/domain/review/model/response/ReviewDetailResponse.java
gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java

- 프론트에서 처리하기 쉽게 해시태그를 List로 반환합니다.  
- 리뷰 1건 조회 API request 변경
- 리뷰 수정 API request 변경
- 리뷰 작성 response 변경
#190

refactor: response 해시태그 타입을 String이 아닌 List로 변경

---

gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupListRepository.java
gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
gusto/src/main/java/com/umc/gusto/global/exception/Code.java

- 원활한 테스트를 위해  GroupList 이미 존재하는 가게 추가를 허용하고 있었습니다. 그러나 앱 사용성을 고려할 때 중복된 가게 추가를 막는 것이 좋을 것 같아 변경합니다.
-  이미 그룹리스트에 추가된 식당을 중복해서 추가하려고 할 경우 이미 존재하는 식당이라는 message를 전달하는 에러처리를 진행했습니다.
- 그룹리스트에 이미 존재하는  가게를 추가 시 에러 발생
close: #187

feat: GroupList 이미 존재하는 가게 추가 시 에러 발생

---

gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupListRepository.java
gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteController.java
gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteListController.java
gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteListRepository.java
gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteRepository.java
gusto/src/main/java/com/umc/gusto/domain/route/service/RouteListService.java
gusto/src/main/java/com/umc/gusto/domain/route/service/RouteListServiceImpl.java
gusto/src/main/java/com/umc/gusto/domain/route/service/RouteService.java
gusto/src/main/java/com/umc/gusto/domain/route/service/RouteServiceImpl.java

-  타인의 루트 조회 시 nickname값을 통해 user 활성화 여부를 먼저 확인하고 이후 루트를 조회하도록 수정 
- API 경로 충돌을 방지하기 위해 RequestParam 값을 통해 nickname 확보로 통일
- 내 루트/ 그룹 루트 목록의 경우 CreateAt기준 최신 순으로 정렬
- 루트리스트의 경우 Ordinal 이동 순서 기준 오름차순으로 정렬
- 타인의 루트 조회 분리 
- 루트 최신 순 정렬
- 타인의 루트 상세 조회 유저 활성화 순서- 루트 조회 순서 변경
- 타인의 루트 상세 조회
- 타인의 루트 조회
- 이동 순서 기준 정렬
- 타인 관련 로직 외에도, 전체적인 정렬이 추가되었습니다.
- 타인 관련 로직과 정렬 로직이 겹치는 RouteRepository코드 변경이 있어 충돌을 방지하고자 하나의 PR로 작성하였습니다
close: #188

refactor: 타인의 루트 조회 API / feat: 정렬 조건 추가

---

gusto/src/main/java/com/umc/gusto/domain/myCategory/service/PinServiceImpl.java
gusto/src/main/java/com/umc/gusto/global/exception/Code.java

- 이미 찜한 가게 중복 찜 불가능하게 합니다.(프론트에서 그럴 상황이 없을 것으로 생각돼 추가하지 않았으나 충돌이 날 수 있으니 대처를 위해 해당 기능을 추가합니다.)
- 가게는 하나의 카테고리에 대해서만 찜할 수 있으므로 카테고리는 상관 없이 가게가 찜이 된 것인지 여부만 확인합니다.
- 찜하기
close: #204

refactor : 이미 찜한 가게 중복 찜 불가

---

gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
gusto/src/main/java/com/umc/gusto/global/exception/Code.java

현재 하나의 리뷰에 여러 번 좋아요 하는 버그를 발견했습니다.  좋아요한 리뷰인지 체크하는 로직을 추가해서 한번만 좋아요할 수 있도록 수정하였습니다. 
#201

fix: 좋아요한 리뷰는 다시 좋아요할 수 없도록 수정

---

gusto/src/main/java/com/umc/gusto/domain/review/entity/Review.java
gusto/src/main/java/com/umc/gusto/domain/review/model/request/CreateReviewRequest.java
gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java

리뷰 건너뛰기를 하게 되면 방문날짜, 디폴트 이미지, 가게가 포함된 리뷰가 생성되어야 합니다. 또한, 건너뛰기한 리뷰는 먹스또 피드에 보이면 안됩니다.
그래서 건너뛰기한 리뷰인지 체크하는 컬럼을 추가하고 먹스또 피드에는 건너뛰기한 리뷰가 나오지 않도록 수정합니다. 
#212

refactor: 리뷰 생성 API에서 리뷰 건너뛰기 상황도 대응할 수 있도록 수정

---

gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetStoreInfoResponse.java
gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java

- store의 category 값을 store엔티티에서 사용
- 현재 지역의 찜한 식당 방문 여부 조회 
close: #210

refactor: 가게 카테고리 참조를 categoryString으로 변경

---

gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java

- 팔로워 리스트 조회 시 팔로워 정보가 아닌 본인의 정보가 return되는 문제
- 잘못된 필드를 참조하고 있었습니다 (`follower`를 참조해야하나 `following`를 참조)
- develop 브랜치로는 추가 PR 없이 commit push 예정입니다.

fix: 팔로워 리스트 조회 시 본인을 return하지 않도록 수정

---

gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
gusto/src/main/java/com/umc/gusto/domain/store/repository/StoreRepository.java

- 가게 조회 시 이미지가 한 가게 리뷰 이미지만 보이는 현상이 있어서 메서드 쿼리문을 변경했습니다.

fix : 가게 조회 시 이미지가 한 가게 리뷰 이미지만 보이는 현상 해결

---

gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
gusto/src/main/java/com/umc/gusto/domain/review/service/FeedServiceImpl.java
gusto/src/main/java/com/umc/gusto/domain/store/repository/StoreRepository.java
gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java

데모데이에서는 5, 33개만 필요하기 때문에 랜덤피드와 피드 검색엔진은 33개, 가게 검색엔진 결과는 3개로 변경합니다. 
#226

refactor: 랜덤 피드, 검색 엔진 API 결과 개수 제한하기

---

gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java
gusto/src/main/java/com/umc/gusto/domain/store/service/StoreService.java
gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java

- 데모데이 이후에 하기로 한 방문여부 조회 기능을 추가했습니다.
* 방문여부는 해당 가게에 리뷰를 작성했는지를 통해 확인한다.
*  visit 쿼리를 엔드포인트에 추가하고 true, false인 boolean 값을 받는다.
close: #229
* 데모데이 이후 추가 수정사항 pr입니다.
* getStoreInMap 메서드에서 findPinsByUserAndMyCategoryIdAndTownNameAndPinIdDESC에서 USER 값에 대한 필터링이 존재하여 처음에는 existByStore만 사용해 방문횟수를 확인했습니다. 그런데 조회 시 user 값에 대한 필터링 없이 조회가 되던군요. 그래서 existByStoreAndUserNickname을 사용해 user 처리를 두번했습니다. 희랑도 방문조회 시 user을 두번 필터링을 거치던데 혹시 왜 그런지 궁금합니다.

refactor : 현재 지역의 카테고리 별 찜한 가게 목록 방문여부 필터링 추가

---

gusto/src/main/java/com/umc/gusto/domain/user/repository/FollowRepository.java
gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java

- 팔로워/팔로잉 목록 반환 시 정렬이 깨져있었고,
페이징 처리를 위한 선택 기준이 잘못되어 페이징 오류가 발생하였습니다.
- 정렬 기준을 추가하였으며, 설계대로 페이징이 작동할 수 있도록 수정하였습니다.

fix: 팔로워 목록 / 팔로잉 목록의 페이징/정렬 수정

---

gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java
gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteController.java
gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteRepository.java
gusto/src/main/java/com/umc/gusto/domain/route/service/RouteService.java
gusto/src/main/java/com/umc/gusto/domain/route/service/RouteServiceImpl.java

- 내/타인의 루트 : 초기값 6개,생성시점을 기준으로 내림차순 정렬, 가장 마지막 routeId값을 기준으로 다음 값부터 6개씩 출력
- 그룹의 루트 : 초기값 6개, 가장 마지막의  routeId값을 기준으로 다음 값부터 6개씩 출력, 
- 내/타인의 루트 
- 그룹의 루트
close: #231

feat: 내/타인의/그룹의 루트 페이징 기능: 루트 커서 기반으로 다음 루트 전달

---

gusto/src/main/java/com/umc/gusto/domain/user/controller/UserController.java
gusto/src/main/java/com/umc/gusto/domain/user/entity/Social.java
gusto/src/main/java/com/umc/gusto/domain/user/model/request/SignInRequest.java
gusto/src/main/java/com/umc/gusto/domain/user/model/request/SignUpRequest.java
gusto/src/main/java/com/umc/gusto/domain/user/model/response/NicknameResponse.java
gusto/src/main/java/com/umc/gusto/domain/user/repository/SocialRepository.java
gusto/src/main/java/com/umc/gusto/domain/user/service/UserService.java
gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
gusto/src/main/java/com/umc/gusto/global/auth/CustomAuthenticationSuccessHandler.java
gusto/src/main/java/com/umc/gusto/global/auth/OAuthService.java
gusto/src/main/java/com/umc/gusto/global/exception/Code.java

- 소셜로그인 인증 주체가 서버 -> 안드로이드 로 변경되어, 관련하여 내용을 수정하였습니다.
- `Social` Entity의 `temporalToken` 필드가 삭제되었습니다. 사용하시는 DB와 일치시켜주시길 바랍니다!
- `Social` Entity의 `socialStatus` 필드의 default 값이 변경되었습니다만, DB에는 영향을 미치지 않습니다.
close: #10 #49

feat: 소셜 로그인 2.0

---

gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java
gusto/src/main/java/com/umc/gusto/domain/group/service/GroupService.java
gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java

- 그룹 페이징 처리 시, 메타데이터가 아닌 hasNext 변수만 반환하도록 수정
- 방문 여부에 따른 가게 목록을 각각 최대 10개 반환하도록 수정
- 그룹 목록 조회
- 그룹 구성원 조회 (현재 그룹 구성원이 3명인 상황)
close: #234 #247

refactor: 그룹 페이징 로직 개선 / 가게 반환값 개수를 10개로 제한

---

gusto/src/main/java/com/umc/gusto/domain/user/controller/UserController.java
gusto/src/main/java/com/umc/gusto/domain/user/model/response/PagingResponse.java
gusto/src/main/java/com/umc/gusto/domain/user/repository/FollowRepository.java
gusto/src/main/java/com/umc/gusto/domain/user/service/UserService.java
gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
gusto/src/main/java/com/umc/gusto/global/exception/Code.java

- 서버의 불필요한 호출을 줄이기 위해 hasNext 변수를 추가 반환합니다.
- Repository에서 List를 반환하던 Method의 return value를 Page로 변경하였습니다.
- 기존 반환값인 FollowResponse를 PagingResponse로 래핑하여 hasNext 값을 반환할 수 있도록 했습니다.
- Page가 존재하지 않는 경우, 에러를 반환합니다.
(`검색할 컨텐츠가 존재하지 않는 경우` or `이전 hasNext 결과가 false이며 더이상 탐색할 수 있는 페이지가 없는 경우`)
- 동작
- 정상 반환
- 검색할 컨텐츠가 존재하지 않는 경우
- 팔로워 목록 조회
- 팔로잉 목록 조회

feat: 팔로워/팔로잉 목록 조회 시 hasNext 여부를 반환

---

gusto/src/main/java/com/umc/gusto/domain/review/model/response/CollectReviewsResponse.java
gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
gusto/src/main/java/com/umc/gusto/domain/review/service/CollectReviewService.java
gusto/src/main/java/com/umc/gusto/domain/review/service/CollectReviewServiceImpl.java

리뷰 모아보기는 방문날짜를 기준으로 정렬되어야 한다. 페이징 처리를 하면 ID(PK)값을 기준으로 방문날짜가 항상 내림차순인 것은 아니다. 즉, 커서 ID가 26이고 방문날짜가 4월 10일이지만 리뷰 ID가 27이고 방문날짜가 4월 2일인게 누락된다.
- 페이징 처리(정렬된)한 응답값에서 가장 작은 리뷰 ID를 커서 ID로 정하는 것이 아니라 정렬되어 가장 마지막 순서에 있는 리뷰를 커서 ID로 지정한다. 이후, 페이징 처리는 커서 ID보다 작은 리뷰 ID이고 커서 ID의 방문날짜보다 같거나 이전 날짜인 리뷰만 가져오도록 한다.
- 더 이상 리뷰가 없을 때 빈 리스트를 반환하는 경우를 예외처리
#250

refactor: 리뷰 모아보기 API시 누락되는 데이터가 보일 수 있도록 수정

---

gusto/src/main/java/com/umc/gusto/domain/user/controller/UserController.java
gusto/src/main/java/com/umc/gusto/domain/user/service/UserService.java
gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
gusto/src/main/java/com/umc/gusto/global/auth/JwtService.java
gusto/src/main/java/com/umc/gusto/global/exception/Code.java

- 로그아웃 api
- refresh-token과 access-token을 인자로 받아 로그아웃 처리 합니다.
- token의 유효성 검사를 한 뒤 Redis에 저장된 토큰 정보를 삭제합니다.

feat: sign-out

---

gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java

- 초대 코드가 URL에 노출되지 않도록 하기 위해 requestbody사용
- 안드 측에서 GET 메소드 사용 시, requestbody로 요청 불가
- POST 메소드 사용과 동시에 URL에 조회의 목적을 명확히 하기 위해 URL도 수정
- 초대 코드로 그룹 정보 조회 API 엔드포인트를 GET에서 POST로 변경
- 목적을 명확히 하기 위해 URL을 /groups/check-invitation으로 수정
close: #267

refactor: 초대 코드로 그룹 정보 조회 API 엔드포인트를 GET에서 POST로 변경

---

gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryService.java
gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java
gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetStoresInMapResponse.java
gusto/src/main/java/com/umc/gusto/domain/store/service/StoreService.java
gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
gusto/src/main/java/com/umc/gusto/domain/user/controller/UserController.java
gusto/src/main/java/com/umc/gusto/domain/user/service/UserService.java
gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
gusto/src/main/java/com/umc/gusto/global/auth/JwtService.java
gusto/src/main/java/com/umc/gusto/global/exception/Code.java

- 프런트의 요청으로 현재 지역의 카테고리 별 찜한 가게 목록 조회 시 카테고리 여러개 처리를 가능하게 하고, 방문 여부에 상관없이 모든 가게를 조회할 수 있도록 한다.
- 현재 지역의 카테고리 별 찜한 가게 목록 API에서 다중 카테고리 클릭 가능하게 처리
- 방문 여부에 상관없이 모두 조회 되도록 하는 조건 추가
- myCategory 다중 처리
- myCategory 다중 처리 및 방문 여부 값이 없을 때 모든 가게 조회
close: #278

refactor : 찜한 가게 목록 조회 시 카테고리 다중 처리 및 방문 여부 조건 수정

---

gusto/src/main/java/com/umc/gusto/global/auth/service/SocialService.java
gusto/src/main/java/com/umc/gusto/global/exception/Code.java

- #240 에서 처리했던 에러 처리가 미흡한 점이 있어 반환하는 에러 메세지를 수정하였습니다.

hotfix: 소셜 에러 케이스 별 에러 메세지 분리

---

gusto/src/main/java/com/umc/gusto/domain/myCategory/controller/MyCategoryController.java
gusto/src/main/java/com/umc/gusto/domain/myCategory/entity/MyCategory.java
gusto/src/main/java/com/umc/gusto/domain/myCategory/model/request/CreateMyCategoryRequest.java
gusto/src/main/java/com/umc/gusto/domain/myCategory/model/request/UpdateMyCategoryRequest.java
gusto/src/main/java/com/umc/gusto/domain/myCategory/model/response/MyCategoryResponse.java
gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/MyCategoryRepository.java
gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryService.java
gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java
gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
gusto/src/main/java/com/umc/gusto/domain/user/entity/User.java
gusto/src/main/java/com/umc/gusto/domain/user/model/request/PublishingInfoRequest.java
gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
gusto/src/main/java/com/umc/gusto/global/exception/Code.java

- 각 카테고리의 공개여부 변경과 마이페이지 내에서 공개여부 변경 로직 추가
- 마이페이지 공개 여부 on일 때만 각 카테고리 공개여부 변경 가능
- 마이페이지 공개 여부 off일 때는 모든 카테고리 공개 여부가 off, on일 때의 공개 여부 값을 기억해 다시 on 상태가 되면 사용
- User의 publishCategory가 PUBLIC일 경우에만 MyCategory의 publishCategory를 수정
- User의 publishCategory가 PRIVATE이 되는 순간, MyCategory의 publishCategory 값이 previousPublishCategory에 저장
- User의 publishCategory가 PUBLIC이 되면, MyCategory의 previousPublishCategory값을 가져와 publishCategory에서 사용
- 타인의 카테고리 조회 시 User의 publishCategory 조회 시 null 처리
- 타인의 카테고리 조회
- 마이페이지 공개여부가 off(PRIVATE)일 때, 카테고리 수정
- 마이페이지 공개 여부가 on(PUBLIC)일 때, 카테고리 조회
- 마이페이지 공개 여부가 off(PUBLIC)일 때, 카테고리 조회
- 마이페이지 공개 여부가 다시 on(PUBLIC)일 때, 카테고리 조회(이전 on 일때 상태 기억)
close: #275

feat : 내 카테고리 개별/전체 공개 여부에 따른 수정 및 추가

---

gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupMemberRepository.java
gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupRepository.java
gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteController.java
gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteListController.java
gusto/src/main/java/com/umc/gusto/domain/route/entity/Route.java
gusto/src/main/java/com/umc/gusto/domain/route/model/request/RouteRequest.java
gusto/src/main/java/com/umc/gusto/domain/route/model/response/RouteResponse.java
gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteRepository.java
gusto/src/main/java/com/umc/gusto/domain/route/service/RouteService.java
gusto/src/main/java/com/umc/gusto/domain/route/service/RouteServiceImpl.java

- 로직 분리: 개인 루트에만 공개, 비공개 여부 존재, 루트명 설정 시 개인과 그룹에 따른 중복성 차이 존재 등으로 로직 분리
- 루트 공개/비공개 여부 기능 추가
- 루트 생성 시 공개/비공개 필드 추가
- 수정작업- 타인의 루트 조회 시 공개된 루트 한정 조건 추가
- 루트 목록 페이지에서 공개/비공개 변경 API 추가
- 그룹루트 로직 분리
- 개인 루트 추가
- 타인의 루트 조회(마이페이지 공개)
- 타인의 루트 조회(마이페이지 비공개)
- 루트 공개여부 변경
- 그룹 루트 추가
- 특이 사항
close: #282

Feat: 루트 공개 비공개 여부

---

gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupMemberRepository.java
gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupRepository.java
gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteController.java
gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteListController.java
gusto/src/main/java/com/umc/gusto/domain/route/entity/Route.java
gusto/src/main/java/com/umc/gusto/domain/route/model/request/RouteListRequest.java
gusto/src/main/java/com/umc/gusto/domain/route/model/request/RouteRequest.java
gusto/src/main/java/com/umc/gusto/domain/route/model/response/RouteResponse.java
gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteListRepository.java
gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteRepository.java
gusto/src/main/java/com/umc/gusto/domain/route/service/RouteListServiceImpl.java
gusto/src/main/java/com/umc/gusto/domain/route/service/RouteService.java
gusto/src/main/java/com/umc/gusto/domain/route/service/RouteServiceImpl.java
gusto/src/main/java/com/umc/gusto/global/exception/Code.java

- 기존에는 루트 생성 시와 식당 추가 시 모두 경로 순서를 입력 받았으나, 추가 시에는 삭제시와 같이 내부적으로 순서 조정에 대한 프론트엔드 요청을 반영 
- ordinal 값을 자동으로 +1 증가
- 마지막 식당 입력 시에는 순서 미입력 시에도 내부적으로 반영하여 순서 조정
- 루트 생성 시 순서 미입력 시에는 에러 발생
- #283 루트공개/비공개 관련 PR을 반영 후 병합해야 함!
close: #285

Feat:  루트 내 이동 경로 순서 자동 부여

---

gusto/src/main/java/com/umc/gusto/domain/route/model/response/RouteRouteListResponse.java
gusto/src/main/java/com/umc/gusto/domain/route/service/RouteListServiceImpl.java
gusto/src/main/java/com/umc/gusto/domain/route/service/RouteServiceImpl.java

- Response에 공개/비공개 여부에 해당하는 변수 추가
- 내 루트 조회
- 루트 상세 조회
close: #283

[refactor] 내 루트 조회할 때나 루트 상세 조회 시 공개/비공개 여부 포함하도록 수정

---

gusto/src/main/java/com/umc/gusto/domain/user/model/request/UpdateProfileRequest.java
gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java

- 프로필 업데이트 시, 서비스 기본 이미지를 선택할 수 있도록 수정했습니다.

feat: 프로필 업데이트 시 기본 이미지 사용 케이스 추가

---

.idea/compiler.xml
.idea/modules/gusto.main.iml
.idea/sqldialects.xml
gusto/src/main/java/com/umc/gusto/domain/review/model/FeedVO.java
gusto/src/main/java/com/umc/gusto/domain/review/model/response/RandomFeedResponse.java
gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
gusto/src/main/java/com/umc/gusto/domain/review/service/FeedServiceImpl.java

- 이유: 랜덤 피드 API에서 500에러가 터지고 있었음
- 원인: repository의 nativeQuery의 경우, entity로 변환이 바로 안된다. VO클래스를 사용해서 받아야 한다. 
원인을 바탕으로 VO클래스를 만들어서 JPA 메소드의 반환 값으로 사용하도록 수정
close: #

fix: 랜덤 피드 API 관련 repository에서 VO를 사용하지 않아 발생한 문제 해결

---

gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java
gusto/src/main/java/com/umc/gusto/global/exception/Code.java

- 타인 카레고리 속 가게 조회 시 User 정보를 안받게 되면서 토큰을 통해 타인 카테고리 조회 시 자신의 닉네임으로 조회하고 있는 지 확인하는 부분이 있었으나 로직상 일어날 가능성이 적다 생각해 삭제하였습니다.
- 타인 카테고리 조회 시 자신의 닉네임으로 조회하고 있는 지 확인하는 부분 삭제
close: #300
* 오류 해결을 위해 코드를 일부 삭제했을 뿐 크게 변한 내용은 없습니다

refactor : 타인의 카테고리 속 가게 조회 시 User 정보 사용하던 에러처리 수정

---

gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
gusto/src/main/java/com/umc/gusto/domain/review/service/FeedServiceImpl.java
gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java
gusto/src/main/java/com/umc/gusto/domain/store/model/response/SearchStoreResponse.java
gusto/src/main/java/com/umc/gusto/domain/store/repository/StoreRepository.java
gusto/src/main/java/com/umc/gusto/domain/store/service/StoreService.java
gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java

- 리뷰 검색에는 페이징 처리가 되어 있으나 가게 검색에 누락되어있습니다.
- 검색 시 대소문자, 공백을 정확히 입력해야 검색되는 상황이었습니다.
- 가게 검색 페이징 처리
- 검색에 사용되는 컬럼에 utf8mb4_general_ci 속성을 추가
해당 속성을 부여하면 데이터를 검색할 때 대소문자와 관계없이 일치 여부를 확인할 수 있습니다.
- 검색 쿼리에 공백을 제거하고 비교하도록 수정
close: #

refactor: 검색 시 대소문자, 공백 무시 & 가게 검색 페이징 처리

---

gusto/src/main/java/com/umc/gusto/global/auth/AuthController.java
gusto/src/main/java/com/umc/gusto/global/auth/CustomAuthenticationSuccessHandler.java
gusto/src/main/java/com/umc/gusto/global/auth/service/AuthService.java
gusto/src/main/java/com/umc/gusto/global/auth/service/SocialService.java
gusto/src/main/java/com/umc/gusto/global/auth/service/UserDetailsService.java
gusto/src/main/java/com/umc/gusto/global/exception/Code.java

- 소셜 로그인 시, 유저 정보를 확인하기 위한 유저 식별값(`소셜 서버 Access Token` 및 `소셜 서버 userId`)에 대한 보안을 강화하기 위한 조치
1. client에서 소셜 서버 로그인을 통해 알아낸 유저 식별값을 암호화하여 서버로 전송
2. gusto 서버에서 암호화된 정보를 복호화한 후, 소셜 서버에 재확인하여 해당 정보가 유효한지 확인
3. 유효한 정보라면, 암호화 상태의 소셜 서버 userId 를 서비스 DB에 저장함
- 해당 PR merge 후 `application.properties`에 추가되는 값들이 있으니 갱신 바랍니다. 
- 해당 PR merge 후 `WebSecurityConfig.java` 파일 갱신이 필요합니다.

feat: 소셜 로그인 정보 암호화

---

gusto/src/main/java/com/umc/gusto/global/auth/AuthController.java
gusto/src/main/java/com/umc/gusto/global/auth/service/AuthService.java
gusto/src/main/java/com/umc/gusto/global/exception/Code.java

- 출시 준비로 백엔드에서 OAuth 로그인(소셜로그인)이 불가능한 상황으로, 백엔드에서 테스트 시 필요한 `access tokens`을 발급받기 위한 API
- API 관련 설명은 노션의 API Sheet를 확인
- `application.properties` 갱신됨

Feat: 백엔드 테스트 시 토큰 발급을 위한 API
